Models/ToDo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToDoApp.Models
{
    public class ToDo
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public bool IsDone { get; set; }
        public string CreatedDate { get; set; }
        public string DueDate { get; set; }
        public string Priority { get; set; }
        public virtual ApplicationUser User { get; set; }
    }

    public enum Priority
    {
        Low,
        Medium,
        High
    }
}

Controllers/ToDoesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToDoApp.Models;

namespace ToDoApp.Controllers
{
    public class ToDoesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ToDoes
        //[Authorize]
        public ActionResult Index()        
        {
            return View();
        }

        //Gets users ToDo list
        private IEnumerable<ToDo> GetMyToDoes()
        {
            string currentUserId = User.Identity.GetUserId();

            ApplicationUser currentUser = db.Users.FirstOrDefault
                (x => x.Id == currentUserId);

            IEnumerable<ToDo> myToDoes = db.ToDos.ToList().Where(x => x.User == currentUser).OrderByDescending(x => x.Id);

            int completeCount = 0;
            foreach (ToDo toDo in myToDoes)
            {
                if (toDo.IsDone)
                {
                    completeCount++;
                }
            }

            if (myToDoes.Count() == 0)
            {
                ViewBag.Percent = 0;
            }
            else
            {
                ViewBag.Percent = Math.Round(100f * ((float)completeCount / (float)myToDoes.Count()));
            }
            
            ViewBag.Completed = "  Completed " + completeCount + " of " + myToDoes.Count() + "  ";
            return myToDoes;
        }

        //Returns Partial view HTM for AJAX script
        public ActionResult BuildToDoTable()
        {
            return PartialView("_ToDoTable", GetMyToDoes());
        }

        //Creates and returns Partial view with tables, so AJAX could refresh items without reloading page
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AJAXCreate([Bind(Include = "Id,Description,Priority,DueDate")] ToDo toDo)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();

                ApplicationUser currentUser = db.Users.FirstOrDefault
                    (x => x.Id == currentUserId);

                toDo.User = currentUser;
                toDo.IsDone = false;
                toDo.CreatedDate = DateTime.Now.ToString("yyyy-MM-dd HH:mm");
                db.ToDos.Add(toDo);
                db.SaveChanges();
            }

            return PartialView("_ToDoTable", GetMyToDoes());
        }

        // GET: ToDoes/Edit/5 Opens Edit ToDo item page
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ToDo toDo = db.ToDos.Find(id);

            if (toDo == null)
            {
                return HttpNotFound();
            }

            string currentUserId = User.Identity.GetUserId();

            ApplicationUser currentUser = db.Users.FirstOrDefault
                (x => x.Id == currentUserId);

            if (toDo.User != currentUser)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(toDo);
        }


        // POST: ToDoes/Edit/5 Saves ToDo from Edit item page
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Description,CreatedDate,IsDone,Priority,DueDate")] ToDo toDo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(toDo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(toDo);
        }


        //Changes ToDo Status to Completed/Uncompleted
        [HttpPost]
        public ActionResult AJAXEdit(int? id, bool value)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (ModelState.IsValid)
            {
                ToDo toDo = db.ToDos.Find(id);
                if (toDo == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    toDo.IsDone = value;
                    db.Entry(toDo).State = EntityState.Modified;
                    db.SaveChanges();
                    return PartialView("_ToDoTable", GetMyToDoes());
                }
            }
            return View();
        }

        //Deletes ToDo record without reloading page
        [HttpPost]
        public ActionResult AJAXDelete(int? id)
        {
            if (ModelState.IsValid)
            {
                ToDo toDo = db.ToDos.Find(id);
                db.ToDos.Remove(toDo);
                db.SaveChanges();
                return PartialView("_ToDoTable", GetMyToDoes());
            }
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/ToDoes/Create.cshtml
@model ToDoApp.Models.ToDo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ToDo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsDone)

                    @Html.ValidationMessageFor(model => model.IsDone, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/ToDoes/Delete.cshtml
@model ToDoApp.Models.ToDo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primery" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/ToDoes/Details.cshtml
@model ToDoApp.Models.ToDo

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ToDo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDone)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/ToDoes/Edit.cshtml
@using ToDoApp.Models

@model ToDo

@{
    ViewBag.Title = "ToDo List Application - Edit";
}

<div style="height: 50px;"></div>
<h4>Edit Record</h4>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)
    @Html.HiddenFor(model => model.CreatedDate)

    <div class="form-group">
        <div class="col-md-10">
            <label for="itemEdit">Item</label>
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", id = "itemEdit", @required = "required" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <label id="modalLabel" for="priorityDropdown">Priority</label>
            @Html.DropDownListFor(model => model.Priority, new SelectList(Enum.GetValues(typeof(Priority))), new { @class = "form-control", id = "priorityDropdown" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <label id="modalLabel" for="itemDate">Due Date</label>
            @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control", id = "itemDate", type = "date" } })

        </div>
    </div>

    <div style="height: 10px;"></div>
    <div class="form-group">
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsDone, new { htmlAttributes = new { id = "completed" } })
                <label id="completedLabel" for="completed"> Completed</label>
                @Html.ValidationMessageFor(model => model.IsDone, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-secondary" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/ToDoes/Index.cshtml
@using ToDoApp.Models

@model ToDo

@{
    ViewBag.Title = "ToDo List Application";
}

<div style="height: 50px;"></div>

<button id="showModal" type="button" class="btn btn-secondary" data-toggle="modal" data-target="#createModal">
    Add New
</button>

<div id="tableDiv"></div>

<div id="todoCreateForm">
    @using (Ajax.BeginForm("AJAXCreate", "ToDoes", new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        UpdateTargetId = "tableDiv"
    }))
    {
        <div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Add New</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group myForm">
                            @Html.AntiForgeryToken()
                            <div>
                                <label for="itemEdit">Item</label>
                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", id = "itemEdit", @required = "required" } })
                                <label id="modalLabel" for="priorityDropdown">Priority</label>
                                @Html.DropDownListFor(model => model.Priority, new SelectList(Enum.GetValues(typeof(Priority))), new { @class = "form-control", id = "priorityDropdown" })
                                <label id="modalLabel" for="itemDate">Due Date</label>
                                @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control", id = "itemDate", type = "date" } })
                                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-secondary" id="btnCreate">Create</button>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@section Scripts {
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Custom_Scripts/BuildTable.js"></script>
    <script src="~/Custom_Scripts/ButtonCreateListener.js"></script>
    <script src="~/Custom_Scripts/ClearModal.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
}

Views/ToDoes/_ToDoTable.cshtml
@model IEnumerable<ToDoApp.Models.ToDo>

<div style="height: 15px;"></div>

<div id="progressBarToDo">
    <p>@(ViewBag.Completed) (@(ViewBag.Percent)%)</p>
    <div class="progress">
        <div class="progress-bar bg-secondary" role="progressbar" style="width:@(Html.AttributeEncode(ViewBag.Percent))%"></div>
    </div>
</div>
<div style="height: 25px;"></div>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th class="text-center" style="width: 10%">
                    Completed
                </th>
                <th style="width: 50%">
                    Item
                </th>
                <th class="text-center" style="width: 10%">
                    Priority
                </th>
                <th class="text-center" style="width: 10%">
                    Created
                </th>
                <th class="text-center" style="width: 10%">
                    Due Date
                </th>
                <th class="text-center" style="width: 5%">
                    Edit
                </th>
                <th class="text-center" style="width: 5%">
                    Delete
                </th>
            </tr>
        </thead>
        <tbody id="tableBody">
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-center">
                        @Html.CheckBoxFor(modelItem => item.IsDone, new { id = item.Id, @class = "ActiveCheck" })
                    </td>
                    <td>
                        @if (!item.IsDone)
                        {
                            @Html.DisplayFor(modelItem => item.Description)
                        }
                        else
                        {
                            <div class="CompetedToDo">@Html.DisplayFor(modelItem => item.Description)</div>
                        }
                    </td>
                    <td class="text-center">
                        @if (item.IsDone)
                        {
                            <span class="CompetedToDo">@Html.DisplayFor(modelItem => item.Priority)</span>
                        }
                        else if (item.Priority == "Low")
                        {
                            <span class="badge badge-success">@Html.DisplayFor(modelItem => item.Priority)</span>
                        }
                        else if (item.Priority == "Medium")
                        {
                            <span class="badge badge-primary">@Html.DisplayFor(modelItem => item.Priority)</span>
                        }
                        else if (item.Priority == "High")
                        {
                            <span class="badge badge-danger">@Html.DisplayFor(modelItem => item.Priority)</span>
                        }
                    </td>
                    <td class="text-center">
                        @Html.DisplayFor(modelItem => item.CreatedDate)
                    </td>
                    <td class="text-center">
                        @if (DateTime.ParseExact(item.DueDate, "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture) < DateTime.Now)
                        {
                            <div class="overdue">@Html.DisplayFor(modelItem => item.DueDate)</div>
                        }
                        else
                        {
                            @Html.DisplayFor(modelItem => item.DueDate)
                        }
                    </td>
                    <td class="text-center">
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    </td>
                    <td class="text-center">
                        <a href="#" id="@item.Id" data-toggle="modal" data-target="#confirm-delete" class="btn btn-danger btn-sm delete delButton">X</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<script src="~/Custom_Scripts/AddCheckBoxListener.js"></script>
<script src="~/Custom_Scripts/BtnDeleteListener.js"></script>